vprusso/toqito

docs/channels.channels.rst, toqito/channels/channels/realignment.py
"realignmnet" -> "realignment"
=> fix a typo in docs

docs/_autosummary/toqito.state_props.log_negativity.rst, tests/test_state_props/test_log_negativity.py, toqito/state_props/__init__.py, toqito/state_props/log_negativity.py
closes #24 .
Log-Negativity with test coverage added. Included in docs.
=> Adding in log_negativity feature

docs/channels.rst, tests/test_channel_props/test_choi_rank.py, toqito/channel_props/__init__.py, toqito/channel_props/choi_rank.py
This PR adds a `choi_rank()` function to `channel_props` and would close #10.
Documentation and tests have been added.
=> Add Choi rank function.

docs/_autosummary/toqito.channel_props.is_trace_preserving.rst, tests/test_channel_props/test_is_trace_preserving.py, toqito/channel_props/__init__.py, toqito/channel_props/is_trace_preserving.py
closes #11 .
Add `is_trace_preserving` function. Tests and docs included.
=> Add is_trace_preserving feature

CHANGELOG.md, README.md, docs/_autosummary/toqito.matrix_props.is_idempotent.rst, docs/matrices.rst, pyproject.toml, tests/test_matrix_props/test_is_idempotent.py, toqito/matrix_props/__init__.py, toqito/matrix_props/is_idempotent.py
Closes #36. Implements functionality to determine whether a given matrix is idempotent.
=> Adding is_idempotent feature

.codecov.yml, .github/CONTRIBUTING.md, .vscode/settings.json, CHANGELOG.md, docs/conf.py, docs/intro_tutorial.rst, docs/tutorials.nonlocal_games.rst, paper/paper.md, pyproject.toml, setup.py, toqito/channels/depolarizing.py, toqito/nonlocal_games/nonlocal_game.py, toqito/perms/perfect_matchings.py
Responding to comments from JOSS review #47.
=> Responding to JOSS review 47 comments.

.codecov.yml, .github/CONTRIBUTING.md, CHANGELOG.md, docs/conf.py, docs/getting_started.md, docs/tutorials.nonlocal_games.rst, tests/test_nonlocal_games/test_extended_nonlocal_game.py, tests/test_nonlocal_games/test_nonlocal_game.py, tests/test_state_opt/test_state_distinguishability.py, toqito/state_opt/state_distinguishability.py
=> Updates from JOSS review

docs/getting_started.md, docs/index.rst, toqito/channel_ops/choi_to_kraus.py, toqito/matrices/clock.py, toqito/matrices/fourier.py, toqito/matrices/gell_mann.py, toqito/matrices/gen_gell_mann.py, toqito/matrices/gen_pauli.py, toqito/matrices/hadamard.py, toqito/matrices/iden.py, toqito/matrices/pauli.py, toqito/matrices/shift.py, toqito/matrix_ops/unvec.py, toqito/matrix_props/is_commuting.py, toqito/matrix_props/is_density.py, toqito/matrix_props/is_diagonal.py, toqito/measurement_ops/measure.py, toqito/measurement_props/is_povm.py, toqito/perms/perm_sign.py, toqito/perms/swap.py, toqito/state_metrics/sub_fidelity.py, toqito/state_opt/state_distinguishability.py, toqito/state_props/in_separable_ball.py, toqito/state_props/purity.py
Responding to comments mentioned in https://github.com/vprusso/toqito/issues/48.
=> Responding to comments in JOSS review 48

paper/paper.md
=> Affiliation fix.

docs/states.rst, tests/test_states/test_singlet.py, toqito/states/__init__.py, toqito/states/singlet.py
The function yields the generalized singlet state acting on two n-dimensional systems. This state is defined as:
`(1/n^2-n) * (eye(n^2) - swap_operator([n, n])`
-  [x] Compute the generalized singlet state
-  [x] I added the tests for the function in  `tests/test_states/test_singlet.py`
-  [x] Added `from toqito.states.singlet import singlet` to `toqito/states/__init__.py`
-  [x] Added the function to the `docs`
=> Feature/singlet [unitaryHACK]

docs/_autosummary/toqito.matrix_props.is_permutation.rst, docs/matrices.rst, tests/test_matrix_props/test_is_permutation.py, toqito/matrix_props/__init__.py, toqito/matrix_props/is_permutation.py
Adds in the feature as requested. 😓 with not much time to go!  😭 
-  😭 Was unable to test the test cases as is yet.  However I ran each one in my own module and they seem to work as expected.
-  😄 Handles cases the mimic permutation matrices by checking each value to non-zero and non-1s as well as adding rows and columns for more accuracy
-   ⚛️ Unsure if it handles cases where the matrix is not 2-dimensional properly
-  None 😸 
-   Ready to be reviewed
So excited.  I was thinking I could get more in however still getting the handle of the whole quantum dev environment that has evolved over the years in concert with git.  
Hoping I can contribute more here and there as time goes on, as I want to play with quantum theories and experiments to understand the universe a little better.
Hope …
=> #66  [unitaryHACK]  is_permutation 

CHANGELOG.md, toqito/channel_ops/partial_channel.py, toqito/matrices/gen_pauli.py, toqito/matrix_ops/tensor.py, toqito/state_metrics/fidelity.py, toqito/state_metrics/matsumoto_fidelity.py, toqito/state_metrics/trace_distance.py, toqito/state_props/schmidt_decomposition.py, toqito/state_props/von_neumann_entropy.py, toqito/states/brauer.py, toqito/states/gen_bell.py
- Remove print statement from `schmidt_decomposition.py`
- Fix "eps" to "epsilon" for math render for `matsumoto_fidelity.py`
- Clean up description of `fidelity.py`.
- Clean up description of `trace_distance.py`.
- Clean up description of `von_neumann_entropy.py`.
- Clean up description of `brauer.py`.
- Clean up description of `gen_bell.py`.
- Clean up description of `partial_channel.py`.
- Clean up description of `gen_pauli.py`.
- Clean up description of `tensor.py`.
- Add changes to `CHANGELOG.md`
=> Small updates to codebase.

.gitignore, CHANGELOG.md, linter.sh, tests/test_channel_metrics/test_diamond_norm.py, toqito/channel_metrics/__init__.py, toqito/channel_metrics/diamond_norm.py, toqito/state_ops/schmidt_decomposition.py
Closes: #19 
- Adding `linter.sh` script for manual linting.
- Adding `diamond_norm.py` for calculating diamond norm.
=> Adding diamond norm.

CHANGELOG.md, tests/test_state_props/test_is_npt.py, toqito/state_props/__init__.py, toqito/state_props/is_npt.py
=> Adding is NPT as feature.

docs/states.rst, tests/test_state_props/test_sk_vec_norm.py, toqito/state_props/__init__.py, toqito/state_props/sk_vec_norm.py
=> Add S(k)-vector norm

tests/test_nonlocal_games/test_extended_nonlocal_game.py, toqito/helper/npa_hierarchy.py, toqito/nonlocal_games/extended_nonlocal_game.py, toqito/state_props/__init__.py
=> [unitaryhack] Adapt NPA hierarchy for extended nonlocal games.

docs/matrices.rst, tests/test_matrix_props/test_sk_norm.py, toqito/helper/__init__.py, toqito/helper/kp_norm.py, toqito/matrix_props/__init__.py, toqito/matrix_props/sk_norm.py
=> Add S(k) - operator norm.

tests/test_channels/test_partial_transpose.py, toqito/channels/partial_transpose.py, toqito/matrix_props/sk_norm.py
This commit fixes some Matlab vs Python differences that were missed when porting the code from QETLAB.
=> Bug fixes in `partial_transpose` and `sk_operator_norm`.

docs/matrices.rst, tests/test_channels/test_partial_transpose.py, tests/test_matrix_props/test_is_block_positive.py, toqito/channels/partial_transpose.py, toqito/matrix_props/__init__.py, toqito/matrix_props/is_block_positive.py, toqito/matrix_props/sk_norm.py
=> [unitaryhack] Add `is_block_positive`.

CHANGELOG.md, tests/test_matrix_props/test_is_block_positive.py, tests/test_matrix_props/test_sk_norm.py, tests/test_state_opt/test_symmetric_extension_hierarchy.py, toqito/helper/kp_norm.py, toqito/helper/npa_hierarchy.py, toqito/matrix_props/is_block_positive.py, toqito/state_ops/schmidt_decomposition.py, toqito/state_opt/state_distinguishability.py
- Updating `CHANGELOG.md` with recent features/fixes
- Minor changes to appease linter.
=> Linter changes and updating CHANGELOG with recent features and fixes

pyproject.toml
Fixing pyproject toml file and setup tools.
=> Fixing pyproject toml.

docs/conf.py
Removes static path from sphinx RTD build.
=> Removing static path

docs/states.rst, tests/test_state_props/test_is_separable.py, toqito/state_props/is_separable.py
Hey @vprusso, sorry it took me a while, but here's my contribution to your implementation of `is_separable` function. The only thing is yet to figure out is on the lines of 152-156 of the `is_separable.py` file. I read the paper referenced there and it seems like one needs to solve an optimization problem there regarding the decomposition of the density matrix, but I haven't figured out how to do that.
=> is_separable function dev

CHANGELOG.md, docs/matrices.rst, pyproject.toml, tests/test_matrices/test_standard_basis.py, toqito/matrices/__init__.py, toqito/matrices/standard_basis.py
=> Adding standard basis feature.

docs/tutorials.nonlocal_games.rst, docs/tutorials.rst, tests/test_matrix_props/test_is_positive_definite.py, toqito/matrix_props/is_positive_definite.py
Using the Cholesky decomposition as a precursory check for positive definiteness.
=> Making positive definite check more rigorous. Adding test cases.

CHANGELOG.md, toqito/random/random_density_matrix.py
=> Fixing random density matrix function.

CHANGELOG.md, tests/test_nonlocal_games/test_xor_game.py, toqito/nonlocal_games/xor_game.py
To address issue #15, I made a `nonsignaling_value` function that creates a `NonlocalGame` object and calls the already existing `nonsignaling_value` function.
(Edit: I have now also fixed a type indicator that I got wrong in last PR)
-  For testing, i adapted the already existing `test_chsh_game_nonsignaling_value` and `test_chsh_game_nonsignaling_value_rep_2`. If there is a better way to do this, feel free to let me know.
=> XOR games: nonsignaling value

CHANGELOG.md, README.md, toqito/channel_metrics/__init__.py
- Fixes failing test for `completely_bounded_spectral_norm`
- Updating `CHANGELOG.md` with recent updates and contributions
=> Fixing test issue for completely bounded spectral norm.

CHANGELOG.md, tests/test_state_opt/test_state_exclusion.py, toqito/state_opt/state_exclusion.py
- Refactor of state exclusion SDP. Function now returns optimal value and measurements and allows user to specify between solving either primal or dual problem.
=> Altering state exclusion solvers for picos.

docs/channels.rst, docs/index.rst, docs/matrices.rst, docs/perms.rst, docs/states.rst, tests/test_matrix_ops/test_vectors_from_gram_matrix.py, tests/test_matrix_ops/test_vectors_to_gram_matrix.py, tests/test_state_opt/test_state_exclusion.py, toqito/matrix_ops/__init__.py, toqito/matrix_ops/vectors_from_gram_matrix.py, toqito/matrix_ops/vectors_to_gram_matrix.py
- Adding Gram matrix functions
- Adding matrices.rst back.
=> Adding functions and fixing docs.

docs/matrices.rst, tests/test_matrix_props/test_is_circulant.py, toqito/matrix_props/__init__.py, toqito/matrix_props/is_circulant.py
=> Adding circulant feature.

tests/test_state_opt/test_state_exclusion.py
Attempt to increase test coverage
=> Adding for test coverage for state exclusion

tests/test_state_metrics/test_matsumoto_fidelity.py, toqito/state_metrics/matsumoto_fidelity.py
Fixes #221 
-  [ ] N/A
-  [ ] N/A
=> Fix test failure

_config.yml
=> Removed config yml file

README.md
Fixes #225 
- Adding Discord `toqito` channel link in README.
=> Adding Discord link to README.

docs/index.rst
=> Updating status buid badge.

docs/index.rst
Fixes https://github.com/vprusso/toqito/pull/255#discussion_r1398227949
-  [ ] TODO 1
=> Remove typo from status build badge

toqito/channel_metrics/diamond_norm.py
=> Adding example section to diamond norm.

toqito/matrix_props/__init__.py, toqito/matrix_props/is_totally_positive.py, toqito/matrix_props/tests/test_is_totally_positive.py
Closes: #273 
- Adding feature to check if matrix is "totally positive"
- Tests for checking this functionality.
=> Adding is totally positive feature.

pyproject.toml, toqito/state_props/is_mutually_unbiased_basis.py, toqito/state_props/tests/test_is_mutually_unbiased_basis.py, toqito/states/__init__.py, toqito/states/mutually_unbiased_basis.py, toqito/states/tests/test_mutually_unbiased_basis.py
Closes #259 
- Feature to generate a MUB in prime dimensions
- Improving function to check if set of vectors is a MUB
- Tests for both MUB and check if MUB.
=> #259-Generate set of mutually unbiased bases

LICENSE, docs/conf.py
As discussed in #229, author and copyright year for the project are updated.
=> Update copyright and authors

toqito/channel_props/is_trace_preserving.py, toqito/channel_props/is_unital.py, toqito/matrix_props/is_totally_positive.py, toqito/state_opt/tests/test_state_exclusion.py, toqito/state_props/tests/test_is_antidistinguishable.py, toqito/state_props/von_neumann_entropy.py, toqito/states/mutually_unbiased_basis.py
=> Fixing pylint and pydocstyle issues.

docs/requirements.txt
=> Fix RTD build failure

toqito/channel_props/tests/test_is_trace_preserving.py
=> Increase coverage for `channel_props/is_trace_preserving`

toqito/channels/tests/test_partial_trace.py
=> Revert "Increase coverage for `partial_trace`"

toqito/state_metrics/tests/test_matsumoto_fidelity.py
=> Pytest - Matsumoto Fidelity

.coveragerc, toqito/helper/tests/test_npa_hierarchy.py, toqito/matrix_ops/tensor.py, toqito/matrix_ops/tests/test_tensor.py
=> Pytest: `toqito/matrix_ops/tensor.py`

docs/states.rst, pyproject.toml, setup.py, toqito/state_props/__init__.py, toqito/state_props/is_product.py, toqito/state_props/is_unextendible_product_basis.py, toqito/state_props/tests/test_is_unextendible_product_basis.py, toqito/states/bell.py
=> Integrate is_upb function

toqito/channel_metrics/tests/test_channel_fidelity.py, toqito/channel_metrics/tests/test_completely_bounded_spectral_norm.py, toqito/channel_metrics/tests/test_completely_bounded_trace_norm.py, toqito/channel_metrics/tests/test_diamond_norm.py, toqito/channel_metrics/tests/test_fidelity_of_separability.py
=> Pytest : `channel_metrics`

toqito/state_opt/tests/test_optimal_clone.py
=> Missing tests: `state_opt/optimal_clone`

.github/workflows/build-test-actions.yml, toqito/channel_ops/tests/test_apply_channel.py, toqito/channel_ops/tests/test_choi_to_kraus.py, toqito/channel_ops/tests/test_dual_channel.py, toqito/channel_ops/tests/test_kraus_to_choi.py, toqito/channel_ops/tests/test_partial_channel.py
=> Pytest: `channel_ops`

.coveragerc
=> Fix pytest bug

toqito/state_props/has_symmetric_extension.py, toqito/state_props/in_separable_ball.py, toqito/state_props/is_mutually_unbiased_basis.py, toqito/state_props/schmidt_rank.py
=> Updating and fixing docstring examples for state props.

toqito/matrix_ops/vectors_from_gram_matrix.py, toqito/perms/symmetric_projection.py
=> Take matrix square root in vectors_from_gram_matrix function

toqito/perms/symmetric_projection.py
=> Fixing docstring for symmetric projection.

.github/workflows/build-test-actions.yml, pyproject.toml, toqito/perms/tests/test_antisymmetric_projection.py
=> macOS in Github Actions

toqito/matrix_props/is_projection.py, toqito/matrix_props/tests/test_is_projection.py
Closes: #362 
- Actually, there was a bug in this function that was indirectly caught in the docstring, so that's good!
=> Fixing bug in projection matrix function.

toqito/state_props/entanglement_of_formation.py, toqito/state_props/tests/test_entanglement_of_formation.py
=> Missing tests: `toqito/state_props/entanglement_of_formation.py`

.github/workflows/update-copyright-year.yml
Fixes #229
Need to make sure this is merged before Dec 31, 2023. The workflow is by default set to update the year on January 1 at 3 am.
=> Automate copyright year

.github/workflows/update-copyright-year.yml
#395 did not work as intended
-  [ ] TODO 1
=> Copyright workflow failure

.github/workflows/update-copyright-year.yml
Related to #404 
-  [ ] TODO 1
=> Copyright year workflow for files not labeled LICENSE

.github/workflows/publish-release.yml
Corrects `yml` synatx error for the workflow added in #396
We did not need to add the first `if` condition as there was already a condition for it in the job.
-  [ ] TODO 1
=> Patch for release workflow

.github/workflows/build-test-actions.yml, pyproject.toml
This satisfies: https://github.com/vprusso/toqito/issues/216?notification_referrer_id=NT_kwDOAghJprM4MjU3NDQ1OTM3OjM0MDk3NTc0#event-11417820401
=> python 3.12 support

docs/_autosummary/toqito.matrices.cyclic_permutation_matrix.rst, docs/_autosummary/toqito.rand.random_circulant_gram.rst
Provide a brief description of the PR's purpose here.
-  [ ] TODO 1
=> Adds new functions in autosummary

.github/workflows/build-test-actions.yml
=> Update CI build strategy

docs/autoapi_members.rst, docs/conf.py, docs/contributing.rst, docs/index.rst, docs/requirements.txt
Fixes #446 
1. https://stackoverflow.com/questions/5599254/how-to-use-sphinxs-autodoc-to-document-a-classs-init-self-method
2. https://github.com/readthedocs/sphinx-autoapi/blob/main/docs/reference/templates.rst
3. https://sphinx-autoapi.readthedocs.io/en/latest/reference/directives.html
4. https://sphinx-rtd-trial.readthedocs.io/en/1.0.8/config.html
5. https://docs.readthedocs.io/en/stable/config-file/v2.html#build
-  [ ] TODO 1
=> AutoAPI + RTD theme: members ordering

toqito/state_opt/ppt_distinguishability.py
=> Sphinx build error

pyproject.toml
=> Python versioning

CHANGELOG.md, toqito/matrix_ops/__init__.py, toqito/matrix_ops/calculate_vector_matrix_dimension.py, toqito/matrix_ops/tests/test_calculate_vector_matrix_dimension.py, toqito/matrix_props/__init__.py, toqito/matrix_props/has_same_dimension.py, toqito/matrix_props/tests/test_has_same_dimension.py, toqito/state_opt/state_distinguishability.py, toqito/state_opt/state_exclusion.py, toqito/state_opt/tests/test_state_distinguishability.py, toqito/state_opt/tests/test_state_exclusion.py, toqito/state_props/is_distinguishable.py
Support for density matrices and vectors for state exclusion and distinguishability
=> Additional support state exclusion and distinguishability

docs/conf.py, pyproject.toml, setup.py
(Needed for releasing to the PyPi server with new version).
=> Updating from 1.0.5 to 1.0.7 (Skipping 1.0.6).

setup.py
Closes #207 
- Added needed lines to include files for `setup.py`.
=> Adding package lines for sdist.

README.md
=> Updating and improving README.

toqito/matrices/gen_gell_mann.py, toqito/matrices/tests/test_gen_gell_mann.py
Resolves: https://github.com/vprusso/toqito/issues/497
-  [x] Refactor to return array
-  [x] Use `ruff` and `pylint` for errors related to code style and formatting.
-  [x] Use `linkcheck` to check for broken links in the …
=> gen_gell_mann refactor

.github/workflows/build-test-actions.yml, .github/workflows/docs.yml, pyproject.toml, toqito/matrix_props/sk_norm.py, toqito/state_props/is_unextendible_product_basis.py
Related to #456 
below.
-  [ ] Use `ruff` and `pylint` for errors related to code style and formatting.
-  [ ] Check the documentation build does not lead to any failures. `Sphinx` build can be checked locally for any failures …
=> Add `toml` dependency groups

docs/tutorials.xor_quantum_value.rst
Closes #607 
(Nice catch, @purva-thakre !)
=> Fixing misplaced & issue.

docs/articles.bib, toqito/state_props/has_symmetric_extension.py
- Updating import based on https://github.com/vprusso/toqito/issues/473
- Minor spelling / grammatical refactor
=> Based on the closure of 473, fixing import.

docs/refs.bib, toqito/matrix_props/__init__.py, toqito/matrix_props/is_doubly_nonnegative.py, toqito/matrix_props/is_nonnegative.py, toqito/matrix_props/is_positive.py, toqito/matrix_props/tests/test_is_doubly_nonnegative.py, toqito/matrix_props/tests/test_is_nonnegative.py, toqito/matrix_props/tests/test_is_positive.py, toqito/states/max_mixed.py
Fixes #557 
Fixes #558 
below.
-  [ ] Check the documentation build does not lead to any failures. `Sphinx` build can be checked locally for any failures related …
=> Add checks for nonnegative, doubly nonnegative and positive matrices

toqito/helper/tests/test_npa_hierarchy.py, toqito/matrix_props/tests/test_is_block_positive.py, toqito/state_props/tests/test_is_separable.py
Adding additional tests for:
- `npa_hierarchy.py`
- `is_block_positive.py`
- `is_separable.py`
=> Adding additional test cases for more coverage.

docs/tutorials.nonlocal_games.rst, toqito/nonlocal_games/nonlocal_game.py, toqito/nonlocal_games/tests/test_nonlocal_game.py
=> Fixing BCS conversion function.

toqito/perms/permute_systems.py
=> Remove csr_matrix and dia_matrix

docs/intro_tutorial.rst
The vectors written are actually "kets" and not "bras", so I corrected it.
Provide a brief description of the PR's purpose here. If your PR is supposed to fix an existing issue, use
a [keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to link your PR to the issue.
below.
Additional information is available in the …
=> typo in docs, updated intro_tutorial.rst

docs/refs.bib, docs/tutorials.nonlocal_games.rst, toqito/nonlocal_games/nonlocal_game.py
=> Adding BCS game docs in nonlocal game tutorial.

docs/index.rst
Add a link to the project repo in left sidebar of the documentation
#844 
below.
- Add repo link
- Add Pypi link
- Add discord link
-  [ ] Check the documentation build does not …
=> Add links in sidebar

.github/dependabot.yml
As discussed in #933 
-  [ ] Use `linkcheck` to check for broken links in the documentation
-  [ ] Use `doctest` to verify the examples in the …
=> Change frequency of dependabot PRs

.github/dependabot.yml
Related to #933 
-  [ ] Use `linkcheck` to check for broken links in the documentation
-  [ ] Use `doctest` to verify the examples in the …
=> Make dependabot ignore minor updates

docs/refs.bib, toqito/state_props/__init__.py, toqito/state_props/common_quantum_overlap.py, toqito/state_props/tests/test_common_quantum_overlap.py
Fixes #460 
[1] added and implemented common quantum overlap feature as common_quantum_overlap.py in state_props directory
[2] added relevant tests for common quantum overlap in state_props/tests directory
[3] modified __init__.py to include common_quantum_overlap
=> feature: common quantum overlap

docs/conf.py
Closes https://github.com/vprusso/toqito/issues/1021
-  [x] modified configurations of `sphinx-copybutton` in `conf.py`
-  [x] Use `linkcheck` to check for …
=> feat(docs): add configuration for copy button prompt behavior

README.md, docs/conf.py, docs/refs.bib, toqito/state_opt/__init__.py, toqito/state_opt/bell_inequality_max.py, toqito/state_opt/optimal_clone.py, toqito/state_opt/state_distinguishability.py, toqito/state_opt/state_exclusion.py, toqito/state_opt/tests/test_bell_inequality_max.py, toqito/state_opt/tests/test_state_distinguishability.py, toqito/state_opt/tests/test_state_exclusion.py
Fixes #563 
Added the implementation for finding the upper bound for the maximum value of a Bell inequality(Issue 563)
Added bell_inequality_max
Added test_bell_inequality_max
Updated matrix_props/_init.py
Updated refs.bib
-  [x] Check the documentation build does not lead to any failures. `Sphinx` …
=> Adding a function that finds the upper bound for a given bipartite Bell inequality

docs/refs.bib, toqito/channels/__init__.py, toqito/channels/phase_damping.py, toqito/channels/tests/test_phase_damping.py
Closes https://github.com/vprusso/toqito/issues/989
-  [x] Added `phase_damping.py` to simulate Phase Damping Channel.
-  [x] Added corresponding coverage tests in `test_phase_damping.py`.
-  [x] Changed `__init__.py` in `toqito/channels`.
-  [x] Check the documentation build does not lead to any …
=> feat: Add Phase Damping Channel

.github/dependabot.yml, .github/workflows/dependabot-automerge.yml
Closes #995 
-  [x] Change : The workflow will automatically merge pull requests that meet the following conditions:
> Update Type:
> 
> 1. Minor version updates
> 2. Patch version updates
> 3. Excludes major version updates
> 
> 
> Dependency Type:
> 
> 1. Direct dependencies
> 2. Development dependencies
-  [x] Verify all previous and newly added unit tests pass in …
=> Feature: automerge update for workflow

README.md, toqito/channel_metrics/diamond_distance.py, toqito/channel_ops/dual_channel.py, toqito/state_props/is_unextendible_product_basis.py
Fixes #1090 
-  [ ] Use `linkcheck` to check for broken links in the documentation
-  [ ] Use `doctest` to verify the examples in the function …
=> Function reference should be a link

.coveragerc
This PR updates the .coveragerc configuration to remove outdated comments and unnecessary ignores, ensuring it aligns with the current project structure.
Updated ```.coveragerc``` file
-  [x] Use `doctest` to verify the examples in the function docstrings work as expected.
=> Updated Coveragerc file

toqito/channel_ops/choi_to_kraus.py, toqito/channel_ops/kraus_to_choi.py, toqito/channels/choi.py, toqito/matrix_ops/unvec.py, toqito/matrix_ops/vec.py, toqito/matrix_props/is_positive_definite.py, toqito/matrix_props/is_stochastic.py, toqito/measurements/pretty_bad_measurement.py, toqito/measurements/pretty_good_measurement.py, toqito/state_props/log_negativity.py, toqito/state_props/negativity.py
fix #1110 
Adding links for documentaion functions
https://drive.google.com/file/d/19rtI01YlUoZ87jVF6guk81DYCvXngUw1/view?usp=sharing
-  [x] Use `linkcheck` …
=> Adding link to documentation functions

docs/contributing.rst
It fixes #1119 
-  [x] Use `doctest` to verify the examples in the function docstrings …
=> Update contributing.rst file

docs/refs.bib, docs/tutorials.superdense_coding.rst
Closes https://github.com/vprusso/toqito/issues/1096
-  [x] Added content in docs/tutorials.superdense_coding.rst
-  [x] Added respective reference in refs.bib
-  [x] Use ruff for errors related to code style and formatting.
-  [x] Verify all previous and newly added unit tests pass in pytest.
-  [x] Check the documentation build does not lead to any failures. Sphinx build can be checked locally for any failures related to your PR
- …
=> Add tutorial for superdense coding

docs/intro_tutorial.rst
added  noise channels to the introductory tutorial
Closes #1112 
-  [x] add noise channel to intro_tutorial
-  [x] Use `linkcheck` to check for broken links …
=> added noise channel examples to intro_tutorial

docs/intro_tutorial.rst
Ref - #1113 
-  [x] Use `doctest` to verify the examples in the function docstrings work …
=> docs(measurements): add code blocks to introductory tutorial

toqito/measurements/pretty_bad_measurement.py
I renamed the variable from pgm to pbm (short for Pretty Bad Measurement) to improve code readability and maintain consistency. It's a good practice to use that relevant variable name.
-  [x] File changed `pretty_bad_measurement.py`
-  [x] Updated variable pgm to pbm
-  [x] Check the documentation …
=> Changed pgm to pbm in pretty_good_measurement.py

.github/dependabot.yml, .github/workflows/dependabot-automerge.yml
Updating the automerge workflow.
-  [ ] pull request needed to be changed from main as main is not the default branch
-  [ ] workflow status removed as it is not necessary as CI is running on every PR automatically
-  [ ] added github.repository == 'vprusso/toqito' for safeguard
-  [ ] reverted the dependabot.yml file as rebase-strategy is anyways "auto" 
-  [ ] Verify …
=> Update: Automerge

toqito/measurement_ops/measure.py, toqito/measurement_ops/tests/test_measure.py, toqito/rand/tests/test_random_density_matrix.py
=> feat: enhance measurement function

.github/PULL_REQUEST_TEMPLATE.md, docs/contributing.rst
Fixes #1095 
-  [ ] Use `linkcheck` to check for broken links in the documentation
-  [ ] Use `doctest` to verify the examples in the function …
=> Update contributing guide

docs/conf.py
A banner is added to each page of the documentation. 
=> Add unitaryHACK announcement to docs

docs/references.rst, docs/refs.bib, toqito/state_props/is_separable.py
=> Check docs build

.github/workflows/build-test-actions.yml, toqito/matrix_ops/tensor_unravel.py, toqito/nonlocal_games/binary_constraint_system_game.py, toqito/nonlocal_games/nonlocal_game.py, toqito/nonlocal_games/tests/test_binary_constraint_system_game.py
=> Add ruff format option in CI

toqito/rand/random_povm.py
=> docs: improve the documentation for the randomness of random_povm

toqito/rand/random_state_vector.py, toqito/rand/tests/test_random_state_vector.py
=> fix: issues with rsv

toqito/state_opt/symmetric_extension_hierarchy.py
=> chore: fix render ovee
