docs/states.rst
tests/test_state_metrics/test_bures_distance.py
toqito/state_metrics/__init__.py
toqito/state_metrics/bures_distance.py

This function takes as input two density matrices and performs the following calculation:
```
from toqito.state_metrics import fidelity
np.sqrt(2.0 * (1.0 - fidelity(rho_1, rho_2)))
```
where `rho_1` and `rho_2 ` are density operators and where the `fidelity` function comes from `toqito.state_metrics.fidelity`.
-  [x] Compute the bures distance
-  [x]  When `rho_1 = rho_2`,  `fidelity(rho_1, rho_2) = 1.0000000000000002`. This will create an error in the `sqrt`. I added the `round` function to the 10 decimal to avoid it.
-  [ ] Perhaps add something in the `fidelity` function for the case  `rho_1 = rho_2` and avoid the numeric error `1.0000000000000002`. That `2` may cause problems somewhere else.

Feature/bures distance [unitaryHACK]

---

tests/test_random/test_random_povm.py
toqito/random/random_povm.py

I noticed a bug in the code of `random_povm` in which running `random_povm(dim, num_inputs, num_outputs)`, where `dim != num_inputs` and `dim != num_outputs` throws an error. It turns out that this is a one-line fix.
I also touched up the docs to state more clearly what the output should look like.

Fix implementation of `random_povm`

---

tests/test_nonlocal_games/test_nonlocal_game.py
tests/test_random/test_random_povm.py
toqito/nonlocal_games/nonlocal_game.py
toqito/random/random_povm.py

When testing my implementation of #62 by trying to calculate the quantum value lower bound of the CHSH game, I got the following error:
```python
ValueError: Invalid dimensions (4, 2). Must be a square matrix.
toqito\nonlocal_games\nonlocal_game.py:361: in quantum_value_lower_bound
alice_povms, lower_bound = self.__optimize_alice(bob_povms)
toqito\nonlocal_games\nonlocal_game.py:392: in __optimize_alice
alice_povms[x_ques, a_ans] = cvxpy.Variable(
..\venv\lib\site-packages\cvxpy\expressions\variable.py:81: in __init__
super(Variable, self).__init__(shape, **kwargs)
```
This is because the current SDP algorithm requires a square matrix  if `PSD` is true, but in the case of the BCS representation of the CHSH game, `num_output_alice = 4` and `num_inputs_alice = 2`.  More info can be found …

Fix implementation of computing the quantum value lower bound of a non-local game

---

tests/test_helper/test_npa_constraints.py
tests/test_nonlocal_games/test_nonlocal_game.py
toqito/helper/__init__.py
toqito/helper/npa_hierarchy.py
toqito/nonlocal_games/nonlocal_game.py

Resolves #5.
Implements a function to calculate an upper bound on the commuting measurement value of a nonlocal game.
-  [x] Is `toqito/helper` the best place for `npa_hierarchy.py` or we should expose the functionality of `npa_constraints` to the user?

NPA hierarchy [unitaryHACK]

---

tests/test_nonlocal_games/test_nonlocal_game.py
toqito/nonlocal_games/nonlocal_game.py

Binary constraint system games are a subset of non-local games that are useful tools for studying non-local games.
This PR implements a constructor for `NonlocalGame` that takes in a list of `m` constraints representing the BCS game and returns a `NonlocalGame`. Each constraint is an `n`-dimensional matrix of shape `2 x 2 x ... x 2`. The `(i, j, k, ...)`-th entry is 1 if and only if the constraint is satisfied given the values v_1 = i, v_2 = j, v_3 = k, ..., and otherwise 0.
Resolves #44.
-  [x] Fix issue with solver for `quantum_value_lower_bound`
-  [x] Implement more tests
Refer to #44.

Implement construction of nonlocal game from binary constraint system game [unitaryHACK]

---

toqito/matrix_ops/unvec.py

Fixed a typo in the `unvec` docstring.

Fix typo in unvec documentation

---

docs/channels.rst
tests/test_channel_props/test_is_quantum_channel.py
toqito/channel_props/__init__.py
toqito/channel_props/is_quantum_channel.py

A function that determines if a given superoperator is a quantum channel. A valid quantum channel is a superoperator that is both trace-preserving and completely positive.
-  [x] Added the tests for the function in `tests/test_channel_props/test_is_quantum_channel.py`
-  [x] Added `from toqito.channel_props.is_quantum_channel import is_quantum_channel` to ` toqito/channel_props/__init__.py`
-  [x] Added the function to the docs

Feature/is_quantum_channel [unitaryHACK]

---

docs/states.rst
tests/test_state_metrics/test_matsumoto_fidelity.py
toqito/state_metrics/__init__.py
toqito/state_metrics/matsumoto_fidelity.py

This implements `matsumoto_fidelity` as described in #28, including documentation and tests.
The implementation is similar to that of `fidelity`, the main difference being that the direct calculation requires at least one of the density matrices to be invertible.
To work around this I adapted the QETLAB implementation: try to invert the matrix with largest determinant; if an error is raised, add a small number `eps` to it. Initially I tried to use machine epsilon, but it created stability problems with the square root. After some trial and error, I found `1e-8` to be a reasonable value (this is also what QETLAB uses).
This works because for singular matrices the limit of zero `eps` is the correct definition of the Matsumoto fidelity (eq. 1.6 in https://arxiv.org/abs/2006.06918). The …

Adding matsumoto_fidelity feature

---

toqito/channels/depolarizing.py

Fixed the link to https://en.wikipedia.org/wiki/Quantum_depolarizing_channel

Fix link in `depolarizing` docstring

---

docs/channels.rst
tests/test_channel_ops/test_dual_channel.py
toqito/channel_ops/__init__.py
toqito/channel_ops/dual_channel.py

This implements `dual_channel` as described in #29 , including documentation and tests.
It accept both one-dimensional and two-dimensional lists for the Kraus representation (as in #79), and outputs the same format.

Adding `dual_channel` feature

---

tests/test_state_props/test_schmidt_decomposition.py
toqito/state_ops/__init__.py
toqito/state_props/__init__.py
toqito/state_props/is_product.py
toqito/state_props/schmidt_decomposition.py
toqito/state_props/schmidt_rank.py

Add functionality for computing the Schmidt decomposition of a density matrix ([issue 59](https://github.com/vprusso/toqito/issues/59)).
- Fixed strange/unexpected behavior on complex state vectors by *not* taking the conjugate of `vt_mat`. Right (conjugate) singular vectors are returned as columns of `vt_mat`, so taking the transpose makes sense. However, taking the conjugate (to recover the singular vectors) leads to strange behavior because the implementation of the tensor product does not take the conjugate of the second argument. 
- Added functionality for computing Schmidt decomposition on arbitrary density operators.
- Consistent with behavior on state vectors, singular operators are returned along last axis of `u_mat` and `vt_mat`.
- Added randomized tests for Schmidt …

Feature: Decomposition of Density Operators

---

tests/test_state_opt/test_symmetric_extension_hierarchy.py
toqito/state_opt/symmetric_extension_hierarchy.py

Fixes a bug where `symmetric_extension_hierarchy` would fail:
```python
from toqito.states import werner
from toqito.state_opt import symmetric_extension_hierarchy
n = 5
states = [werner(n, -1.0), werner(n, 1.0)]
res = symmetric_extension_hierarchy(states=states, probs=None, level=1)
```
The source of the problem was a miscalculation of the dimensions of the two sub-systems that states live.
In addition, this PR introduces an extra optional arg `dim` which allow users to define the dimensions of the
sub-systems since we assume they're equal by default.

Fix dimension handling in `symmetric_extension_hierarchy`.

---

pyproject.toml

Downgrading `setuptools<58` for RTD and `cvx`

Attempting to fix RTD setuptools.

---

pyproject.toml

Attepted fix for `error in cvxpy setup command: use_2to3 is invalid.`

Fixing pyproject toml.

---

tests/test_matrix_props/test_is_block_positive.py
tests/test_matrix_props/test_sk_norm.py
tests/test_nonlocal_games/test_extended_nonlocal_game.py
toqito/nonlocal_games/extended_nonlocal_game.py
toqito/states/max_entangled.py
toqito/states/max_mixed.py

- Adding `hermitian=True` to `commuting_measurement_value_upper_bound`. 
- Adding `cvxpy.real()` in `cvxpy.Maximize` in `commuting_measurement_value_upper_bound`.
- Adding `rtol` and `atol` threshold to tests
- Removing deprecated `sparse.dia.dia_matrix` to `sparse.dia_matrix`

Minor fixes and improvements.

---

tests/test_nonlocal_games/test_xor_game.py
toqito/nonlocal_games/xor_game.py

Adds parallel repetition for XOR games by bridging over to the generic NLG version of the function.
-  Would it be better to only create a new NLG object if `reps>1` and use the already existing XOR function otherwise? It might yield some small performance benefits, but I'm not sure.
My apologies for the long silence – I was quite busy the last few weeks. I also built a separate `classical_value` function to avoid having to create a `NonlocalGame` object, but it is incredibly slow and doesn't seem to like it when `q_0, q_1 > 2`.
This solution seems a bit underwhelming, but it works, and seems to run fairly quickly as well.

Parallel repetition for XOR games

---

.github/CONTRIBUTING.md
docs/getting_started.rst
pyproject.toml

Fixes #150
When `pip install -e.` is used, the dependencies listed in `pyproject.toml` are not installed. I had to manually install them because I couldn't figure out a way to do something like `pip install dev_dependencies`.  A line for this is currently missing. 
Something to keep track of is `black` and `flake8` will flag quite a few formatting issues when I run `black toqito/` and `flake8 toqito/`.

Update contribution guidelines

---

tests/test_matrix_props/test_sk_norm.py

Fixes #151 by relaxing the numerical tolerance of the equality check.

Fixes Sk-norm failing test case.

---

tests/test_helper/test_channel_dim.py
toqito/helper/__init__.py
toqito/helper/channel_dim.py

This commit adds a helper function to compute the input, output and environment dimensions of a channel. It will be used in subsequent PRs to fix places where we try to retrieve the dimensions of the channel.
Closes #32

Add `channel_dim`.

---

tests/test_channel_ops/test_dual_channel.py
tests/test_channel_ops/test_kraus_to_choi.py
tests/test_channel_props/test_is_unital.py
toqito/channel_ops/dual_channel.py
toqito/channel_ops/kraus_to_choi.py
toqito/channel_props/is_unital.py

There are places where we failed to retrieve the input and output dimensions of a general channel. This commit uses the recently added function `channel_dim` and fixes:
1. `kraus_to_choi` if non square input. Additionally flat list for CPTP channels are now supported (related to #79). 
2. `is_unital` if unequal input and output dims.
3. `dual_channel` if non square input and output.

Use `channel_dim`.

---

tests/test_channel_ops/test_choi_to_kraus.py
tests/test_matrix_ops/test_unvec.py
toqito/channel_ops/choi_to_kraus.py
toqito/matrix_ops/unvec.py

Previously `choi_to_kraus` was able to output a correct answer only for completely positive channels.
This commit drops this constraint and adds support for all channels which are generally described by
pairs of left and right Kraus operators.
Related to #74.

`choi_to_kraus` for non CP maps.

---

tests/test_channel_ops/test_choi_to_kraus.py
toqito/channel_ops/choi_to_kraus.py

This commit fixes an oversight in `choi_to_kraus` where we failed to build correctly the right Kraus operators for non-positive hermitian-preserving channels. (we forgot to discard small eigenvalues!!)

Minor fix in `choi_to_kraus`.

---

tests/test_channel_props/test_is_unitary.py
toqito/channel_props/is_unitary.py

Previously the check in place was not sufficient to determine if a channel is unitary. We should assert that the channel is described by one Kraus operator and this matrix is unitary.

Fix `is_unitary` for channels.

---

tests/test_channels/test_partial_trace.py
tests/test_channels/test_partial_transpose.py
tests/test_matrix_props/test_is_block_positive.py
tests/test_matrix_props/test_majorizes.py
tests/test_state_props/test_is_separable.py
toqito/channel_metrics/channel_fidelity.py
toqito/channel_props/is_trace_preserving.py
toqito/channels/partial_trace.py
toqito/channels/partial_transpose.py
toqito/channels/realignment.py
toqito/matrix_props/majorizes.py
toqito/matrix_props/sk_norm.py
toqito/nonlocal_games/quantum_hedging.py
toqito/state_opt/optimal_clone.py
toqito/state_opt/symmetric_extension_hierarchy.py
toqito/state_props/entanglement_of_formation.py
toqito/state_props/has_symmetric_extension.py
toqito/state_props/is_ppt.py
toqito/state_props/is_separable.py
toqito/state_props/log_negativity.py
toqito/state_props/negativity.py

Fix: #145
This PR refactored ```partial_trace``` and ```partial_transpose```.

Refactor partial_trace and partial_transpose

---

docs/_autosummary/toqito.state_metrics.bures_angle.rst
docs/states.rst
tests/test_state_metrics/test_bures_angle.py
toqito/state_metrics/__init__.py
toqito/state_metrics/bures_angle.py

Add bures angle state metric to close #171 
-  [x] Add bures angle in state metrics
-  [x] Add test for bures angle
-  [x] Add bures angle to documentation

Add bures angle

---

.flake8

The config file for flake8has been added. The rule E203 is now excluded to ensure compatibility of black and flake8.

Ensure compatibility of black and flake8 (#180)

---

docs/tutorials.rst
toqito/channel_metrics/completely_bounded_spectral_norm.py
toqito/channel_metrics/completely_bounded_trace_norm.py
toqito/channel_metrics/fidelity_of_separability.py
toqito/matrices/standard_basis.py
toqito/matrix_ops/outer_product.py
toqito/matrix_props/sk_norm.py
toqito/state_metrics/hilbert_schmidt_inner_product.py
toqito/state_props/is_npt.py
toqito/state_props/is_separable.py

Fixes #152 
-  [ ] TODO 1
-  [x] It might be better to have a reference file labeled `refs.bib` instead of manually inserting a reference list in docstrings of functions. 

Doc Build Warnings

---

toqito/channel_metrics/completely_bounded_trace_norm.py
toqito/matrix_ops/inner_product.py
toqito/matrix_ops/outer_product.py
toqito/matrix_props/is_diagonally_dominant.py
toqito/matrix_props/trace_norm.py
toqito/nonlocal_games/xor_game.py
toqito/state_opt/state_exclusion.py

Pydocstyle Errors

---

tests/test_channel_metrics/test_channel_fidelity.py
toqito/channel_metrics/channel_fidelity.py

Update coverage for channel_fidelity

---

tests/test_channel_metrics/test_completely_bounded_trace_norm.py

Fixes #233 
-  [x] N/A
-  [x] N/A

Update pytest coverage for CB trace norm

---

.readthedocs.yml

Fixes deprecation from https://blog.readthedocs.com/use-build-os-config/

Attempt to fix deprecation for RTD.

---

toqito/matrix_ops/tests/test_vectors_from_gram_matrix.py
toqito/matrix_ops/vectors_from_gram_matrix.py
toqito/state_opt/ppt_distinguishability.py
toqito/state_opt/state_exclusion.py

Had a silly bug that I patched for `state_exclusion`.

Fixing bug in state exclusion code.

---

toqito/channels/tests/test_partial_trace.py

Fixes #236 
-  [x] Check uncovered line is covered
-  [x] Consolidate remaining tests using parametrize
-  [x] Rebase this PR before merging if #302 is merged before this one. 
-  [x] pylint flagged some things, probably will flag fewer when remaining tests are moved into the new changes. The lines are unrelated to the changes I made. Mostly due to a variable of the same name defining a different thing outside the test. 
```
toqito/channels/tests/test_partial_trace.py:68:4: W0621: Redefining name 'test_input_mat' from outer scope (line 9) (redefined-outer-name)
toqito/channels/tests/test_partial_trace.py:90:4: W0621: Redefining name 'test_input_mat' from outer scope (line 9) (redefined-outer-name) …
```

Increase coverage for `partial_trace`

---

docs/_autosummary/toqito.matrix_props.is_linearly_independent.rst
docs/_autosummary/toqito.matrix_props.is_totally_positive.rst
docs/_autosummary/toqito.states.bb84.rst
docs/_autosummary/toqito.states.mutually_unbiased_basis.rst
docs/_autosummary/toqito.states.trine.rst
docs/articles.bib
docs/matrices.rst
docs/states.rst
toqito/matrix_ops/vectors_to_gram_matrix.py
toqito/matrix_props/__init__.py
toqito/matrix_props/is_linearly_independent.py
toqito/matrix_props/is_totally_positive.py
toqito/matrix_props/tests/test_is_linearly_independent.py
toqito/state_opt/tests/test_ppt_distinguishability.py
toqito/states/mutually_unbiased_basis.py

Adding check for linear independence.

---

.github/workflows/build-test-actions.yml
pyproject.toml

Fixes #220 
The changes in this PR follow from https://docs.codecov.com/docs/github-2-getting-a-codecov-account-and-uploading-coverage#create-ci-pipeline
-  [ ] TODO 1

Remove coveralls

---

toqito/matrix_props/is_block_positive.py
toqito/matrix_props/tests/test_is_block_positive.py

Related to some uncovered lines in #241
Last line is still not covered by this PR.  
-  [ ] TODO 1

Missing tests: `is_block_positive`

---

docs/rand.rst
pyproject.toml
toqito/rand/__init__.py
toqito/rand/random_states.py
toqito/rand/tests/test_random_states.py

added random_states function and its test as described in issue #380 
-  [ ] Implemented random_state function in rand/random_states.py
-  [ ] Implemented its test in rand/test/test_random_states.py

feat: added random_states func + tests

---

.github/workflows/publish-release.yml

Fixes #358 
Fixes #359
Broken link for image at this link: https://pypi.org/project/toqito/
-  [ ] TODO 1

Automate release and release notes

---

.github/workflows/build-test-actions.yml
docs/getting_started.rst
toqito/perms/tests/test_antisymmetric_projection.py

Resolves: https://github.com/vprusso/toqito/issues/399
Same issue: https://github.com/scikit-learn/scikit-learn/issues/10562 tests were failing only for `macos` with `np.testing.assert_allclose`.
https://github.com/numpy/numpy/issues/7726 discussion on why numpy [informs](https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_allclose.html#numpy.testing.assert_allclose) users that `allclose` is the equivalent to `np.testing.assert_allclose` when they provide different default values.
Another discussion: https://github.com/numpy/numpy/issues/3183#issuecomment-350892896
Based on both of these discussions, not much came out of them. It really comes down to maintainers to set the path forward for issues like this. It's hard to say what the core issue is exactly. ~~One can say …

macos failure fix

---

toqito/matrices/__init__.py
toqito/matrices/gen_pauli.py
toqito/matrices/gen_pauli_x.py
toqito/matrices/gen_pauli_z.py

As requested in #478, I have replaced all the variables/comments/function-names/file-names occurrences from shift to gen_pauli_x and clock to gen_pauli_z.
If at all there are any issues regarding these code changes, then do let me know.
Sincere apologies if I have missed any code to be changed or implemented a code incorrectly.
Kindly let me know if any changes are required.
-  [X] Name change of shift/clock to gen_pauli_x/gen_pauli_z.

Fix #478 : Rename shift and clock matrices to gen_pauli_x and gen_pauli_z

---

toqito/perms/antisymmetric_projection.py
toqito/perms/tests/test_antisymmetric_projection.py

Closes: https://github.com/vprusso/toqito/issues/498
-  [x] Refactor `antisymmetric_projection.py`
-  [x] Update `test_antisymmetric_projection.py`
-  [x] Use `ruff` and `pylint` for errors related to code style and formatting.
-  [x] Use `doctest` to verify the examples in the function docstrings work as expected.

Refactor antisymmetric_projection

---

docs/articles.bib
docs/autoapi_members.rst
docs/conf.py
toqito/matrix_props/kp_norm.py
toqito/measurements/__init__.py
toqito/measurements/pretty_bad_measurement.py
toqito/measurements/pretty_good_measurement.py
toqito/measurements/tests/__init__.py
toqito/measurements/tests/test_pretty_bad_measurement.py
toqito/measurements/tests/test_pretty_good_measurement.py

Closes #147 
Adding the ability to generate a set of either "pretty good" or "pretty bad" measurement operators.

Pretty good pretty bad measurements

---

toqito/matrices/pauli.py
toqito/matrices/tests/test_pauli.py

Closes: https://github.com/vprusso/toqito/issues/529
I left `is_sparse` in for the moment even though it's not technically being used in `pauli.py` due to the test cases relying on True or False. Would it make sense to completely remove `is_sparse` and drop `True` from the test cases? @purva-thakre  I believe so, but drafting this for PR for now.
-  [x] Remove `csr_matrix`
-  [x] Use `ruff` and `pylint` for errors related to code style and formatting.
-  [x] Use `doctest` to verify the examples in the function …

pauli refactor

---

.gitignore
docs/contributing.rst

Simplifying gitignore file.

---

toqito/matrices/gen_pauli_x.py

Eliminate the reassignments in the gen_pauli_x construction by rolling along an axis.

matrices: simplify gen_pauli_x construction

---

toqito/state_props/has_symmetric_extension.py
toqito/state_props/is_antidistinguishable.py
toqito/state_props/is_distinguishable.py

Fixes #473 
This is technically **not a fix** as we have to specify the full import path for a bunch of files only. If this is indeed the source of the issue where Python could not distinguish between the module and functions, we should rename all `.py` files to not have the same names as the functions in them. 
For example, rename `toqito/state_props/is_antidistinguishable.py` to `toqito/state_props/is_antidistinguishable_function.py`
below.
-  [x] Added full import path for the failing doctest examples
Before marking your PR ready for review, make sure you checked the following locally. If this is your first PR, you might be notified of some workflow failures after a …

Random doctest failures

---

docs/articles.bib
docs/tutorials.extended_nonlocal_games.rst
docs/tutorials.nonlocal_games.rst
docs/tutorials.state_distinguishability.rst
docs/tutorials.state_exclusion.rst
docs/tutorials.xor_quantum_value.rst

References in the tutorials have been fixed as per the guidelines in #401. Fix is part of the Unitary Hack 2024.
Fixes #401 
The changes are listed below.
- The references have automatically been updated in each tutorial using the Spinx tool.
- Some references in the tutorials were missing from the articles.bib file, so I have added them using the same style as recommended.

Fix for Issue #401

---

.github/workflows/build-test-actions.yml

Some users mentioned that regenerating the token and updating it in the `.yml` file fixed this issue for them. Not sure if this will work, but let's hope!

Regenerated and updated codecov token.

---

toqito/state_props/is_separable.py

Current:
Want:
below.
-  [ ] Check the documentation build does not lead to any failures. `Sphinx` build can be checked locally for any failures related to your …

Code block in `is_separable`

---

docs/articles.bib
toqito/matrix_ops/tests/test_vector_to_density_matrix.py
toqito/state_opt/ppt_distinguishability.py
toqito/state_opt/state_distinguishability.py
toqito/state_opt/state_exclusion.py
toqito/state_opt/tests/test_state_distinguishability.py
toqito/state_opt/tests/test_state_exclusion.py

Enable the ability for the user to unambiguously exclude or discriminate amongst of quantum states in the state_distinguishability.py and state_exclusion.py files, respectively. Fixes #519 
below.
-  [x] Verify all previous and newly added unit tests …

Add unambiguous discrimination strategy to state distinguishability and state exclusion

---

docs/articles.bib
toqito/state_props/is_separable.py
toqito/state_props/tests/test_is_separable.py

This is for issue #518 
below.
-  [X] Added several conditions porting from the MATLAB implementation. I believe only 1-2 relative checks (found to be slower, as written in the MATLAB code comments) are omitted.
-  [X] Use `ruff` for errors related to code style and formatting.
-  [X] Verify all previous and newly …

Add more conditions for checking `is_separable`

---

docs/intro_tutorial.rst
toqito/states/ghz.py
toqito/states/tests/test_ghz.py

Closes: #536 
- Removed `sparse.lil_matrix` from `ghz.py`
- Updated tests and docs (no longer need to use `.toarray()`.

Removed lil sparse matrix for GHZ state.

---

toqito/perms/symmetric_projection.py
toqito/perms/tests/test_symmetric_projection.py

Closes #537 
- Removing `scipy.sparse` in `symmetric_projection.py`
- Small simplifications and improvements to `symmetric_projection.py`
- Adding more tests in `test_symmetric_projection.py`.

Removing sparse matrix for symmetric projection.

---

toqito/helper/tests/test_update_odometer.py

Add pytest to unit tests for `update_odometer`

---

toqito/rand/__init__.py
toqito/rand/random_circulant_gram_matrix.py
toqito/rand/tests/test_random_circulant_gram_matrix.py

Hi,
This PR fixes #675.
To maintain project consistency, I have appended "matrix" to the relevant file and function names. Additionally, I have updated the associated documentation and tests.
Best,
Fabien

Rename Random Circulant Gram to Random Circulant Gram Matrix

---

docs/refs.bib
toqito/matrix_props/__init__.py
toqito/matrix_props/is_anti_hermitian.py
toqito/matrix_props/tests/test_is_anti_hermitian.py
toqito/matrix_props/tests/test_is_hermitian.py

Adds the `is_anti_hermitian` function to `matrix_props`. Fixes #766.
below.
-  [x] Adds the `is_anti_hermitian` function to `matrix_props`. The function internally uses `is_hermitian` to limit code duplication.
-  [x] Verify all previous and newly …

Added is_anti_hermitian.py

---

docs/conf.py

Multiple PRs show the `linkcheck` workflow failing due to a `403` error. This PR temporarily ignores all the broken links until I figure out a solution to it. 
The diff in this PR copies the changes to `conf.py` in https://github.com/unitaryfund/mitiq/pull/2332
below.
-  [ ] Use `ruff` for errors …

Ignore APS links in linkcheck

---

setup.py

Removing scikit-image from setup.py.

---

toqito/nonlocal_games/extended_nonlocal_game.py
toqito/nonlocal_games/nonlocal_game.py

Fixing the multiple warnings as shown in:
https://github.com/vprusso/toqito/actions/runs/11151893975/job/30996320621?pr=821#step:5:3446

Fixing multiplication operator warning for extended nonlocal games.

---

docs/refs.bib
toqito/matrix_props/is_orthonormal.py
toqito/rand/__init__.py
toqito/rand/random_orthonormal_basis.py
toqito/rand/tests/test_random_orthonormal_basis.py

Random orthonormal basis in matrix_props

---

docs/refs.bib
docs/tutorials.extended_nonlocal_games.rst
toqito/rand/random_circulant_gram_matrix.py

Closes #275 
- Normalizes all references.
- Adding clickable URL field for all references.

Initial check to see if adding url field breaks things.

---

CHANGELOG.md

Provide a brief description of the PR's purpose here. If your PR is supposed to fix an existing issue, use
a [keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to link your PR to the issue.
below.
-  [ ] Use `ruff` for errors related to code …

Changelog v1.1.0

---

docs/tutorials.nonlocal_games.rst

Provide a brief description of the PR's purpose here. If your PR is supposed to fix an existing issue, use
a [keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to link your PR to the issue.
This PR is created to pass the check in the non-local games example. Since the optimal value for the chsh quantum probability is getting stuck in a suboptimal range, an approach to overcome this is running the check multiple times so as to maximize the chances to reach the optimal solution.
This has been discussed in detail in the discussion[here](https://github.com/vprusso/toqito/pull/835#issuecomment-2407326088).
#Resolves #613
Notable changes that this PR has either accomplished or will accomplish. Feel free to add more lines to the …

Non-local games check pass

---

docs/tutorials.nonlocal_games.rst

This PR resolves the flacky non-local games docstring example. The fix is the same as the earlier fix in #613.
#Resolves #873.
-  [x] Added multiple runs in the non-local games example to prevent getting suboptimal solution.
-  [x] Check the documentation build does not lead to any failures. …

Fix non-local games example

---

docs/refs.bib
toqito/states/chessboard.py

This PR fixes the references for the states/chessboard.py as discussed in the mentioned issue.
#Closes #843
-  [x] Added "Bruß_2000_Construction" reference in refs.bib
-  [x] Modified reference in chessboard.py
-  [x] Check the documentation build does not lead to any failures. `Sphinx` build can be …

Fixed chessboard references

---

toqito/nonlocal_games/nonlocal_game.py

Adding parallelism using `multiprocessing` python library. Added a new function `process_iteration` that provides reusability of code. the parallelization is done when `num_alice_outputs**num_bob_inputs` is more than 1000.
#Resolves #12
-  [x] Added a helper method to invoke multiprocessing when needed.
-  [x] Verify all previous and newly added unit tests pass in …

Parallelize classical value in nonlocal games

---

.pre-commit-config.yaml
docs/contributing.rst

Fixes #912 
This PR introduces a pre-commit hook configuration for the repository to improve code quality and enforce consistent coding practices.
-  [x] Added a `.pre-commit-config.yaml` file to configure pre-commit hooks.
-  [x] Modified `docs/contributing.rst` to include guidelines for using pre-commit hooks.
Before marking your PR ready for review, make sure you checked the following locally. If this is your first PR, you might be notified of some workflow failures after a maintainer has approved the workflow jobs to be run on your PR.
-  [x] Verify all previous and newly added unit tests pass …

Added pre-commit Hook

---

toqito/channel_ops/__init__.py
toqito/channel_ops/natural_representation.py
toqito/channel_ops/tests/test_natural_representataion.py

Closes #885 
-  [ ] Implemented `natural_representation` function to convert Kraus operators into their natural representation. 
-  [ ] Added unit tests to validate correctness, including cases for identity, bit-flip, amplitude damping, and depolarizing 
-  [ ] Ensured input validation for empty lists, incorrect types, and mismatched dimensions.  
-  [ ] Verify all …

Feature: Kraus operator to natural represention

---

README.md

This Pull Request addresses issue [#998](https://github.com/vprusso/toqito/issues/998). I made the following changes in the README:
1. **Rename “Unitary Fund” to “Unitary Foundation”**  
- Updated all text references to use the new name.
2. **Align Badge Style**  
- Modified the badges following the example from [this reference README](https://github.com/unitaryfund/metriq-gym/blob/main/README.md).  
- Adjusted badge format and links to match the desired style.
These changes focus on **documentation and styling**; they do not affect any core functionality of the project.
- Feedback or further suggestions are welcome.  
- Thank you for reviewing this Pull Request!

Update badges in README to reflect Unitary Foundation name

---

README.md

Removed a broken link from the README that pointed to a non-existent toqito homepage. Since no dedicated landing page exists, this line was removed entirely as suggested in the issue discussion.
Fixes Issue #1002 
-  [ ] Removed the broken link from the README
-  [x] Check the documentation build …

Removed broken link to toqito homepage from README

---

README.md
docs/index.rst

This Pull Request addresses the additional feedback from [@vprusso](https://github.com/vprusso) regarding the documentation and badge style:
1. **Documentation Page Update**  
- Updated the `docs/index.rst` file to ensure the name and badge references are consistent with the recent changes.
2. **Badge Style Change**  
- Changed the badge style from **"plastic"** to match the style used in [the linked reference page](https://raw.githubusercontent.com/unitaryfund/metriq-gym/refs/heads/main/README.md). This ensures visual consistency across the project.
These updates build on the previous changes by refining documentation and improving the user-facing badges. As always, feedback or further suggestions are welcome.
- Please let me know if there are any other documentation sections that need …

Update style plastic and include Unitary Foundation name in index.rst

---

toqito/matrix_props/__init__.py
toqito/matrix_props/is_pseudo_unitary.py
toqito/matrix_props/tests/test_is_pseudo_unitary.py

Added feature to check if a matrix is pseudo unitary (in regards to [Issue 767](https://github.com/vprusso/toqito/issues/767)).
-  Added is_pseudo_unitary
-  Added test_is_pseudo_unitary
-  Updated matrix_props/__init_.py
-  [X] Use `ruff` for errors related to code style and formatting.
-  [X] Verify all previous and newly added unit tests pass in `pytest`.
-  [X] Check the documentation build does not lead to any failures. `Sphinx` …

Add is_pseudo_unitary

---

poetry.lock
pyproject.toml
setup.py
toqito/channel_metrics/channel_fidelity.py

Fixes #1040 
-  [x] Removed explicit installation of cvxopt from `setup.py`, `pyproject.toml`
-  [x] Added the usage of `solver = SCS` instead of `solver=CVXOPT` for a `problem` method defined in `cvxpy` in file `toqito/channel_metrics/channel_fidelity.py`
-  [x] Check the documentation build does …

Removing explicit cvxopt dependency

---

pyproject.toml
toqito/matrix_props/is_positive_definite.py
toqito/matrix_props/tests/test_is_block_positive.py
toqito/matrix_props/tests/test_is_positive.py
toqito/matrix_props/tests/test_is_stochastic.py
toqito/state_opt/state_distinguishability.py
toqito/state_opt/state_exclusion.py

Fixes #1045 
After facing some version control issues in the previous (almost the same) PR #1046, the following pr was created.
The issue was:
`ruff lint` was not removing unused imports due to not selecting "F401" for `tool.ruff.lint` in the `pyproject.toml` file
-  [x] Fixed `pyproject.toml`
-  [x] Removed unused imports from `matrix_props/is_positive_definite.py`
-  [x] Removed unused imports from  `matrix_props/tests/test_is_block_positive.py`
-  [x] Removed unused imports from  `matrix_props/tests/test_is_positive.py`
-  [x] Removed unused imports from  `matrix_props/tests/test_is_stochastic.py`
-  [x] Removed unused imports from  `state_opt/state_exclusion.py`
Further changes:  
-  [x] Removed unused imports from `state_opt/state_distinguishability.py`
-  [x] Changed `ruff target …

fix:pyproject.toml lint for unused imports removal

---

toqito/rand/random_density_matrix.py
toqito/rand/random_orthonormal_basis.py
toqito/rand/random_unitary.py
toqito/rand/tests/test_random_density_matrix.py
toqito/rand/tests/test_random_orthonormal_basis.py
toqito/rand/tests/test_random_unitary.py

Fixes #1031 
This bug was noticed, and a probable solution was put forward by @tnemoz; thanks!
The bug was related to the `rand` module not producing the unitary/orthogonal matrix according to the Harr distribution.
-  [x] Fixed the bug by changing `random distribution` with a 'standard distribution` causing the issue in `rand/random_unitary.py`
-  [x] Updated the `test` files  `test_random_density_matrix.py`, `test_random_orthonormal_basis.py` and `test_random_unitary.py`
Additional information is available in the …

fix: `random_unitary` doesn't sample from the Haar distribution

---

toqito/matrix_ops/vec.py

This PR fixes the vec operator documentation in matrix_ops/ so it correctly describes the function’s behavior (column stacking using Fortran order) and updates the math example accordingly.
Fixes #1073

Update docstrings in matrix_ops/vec.py 

---

toqito/channel_props/__init__.py
toqito/channel_props/is_extremal.py
toqito/channel_props/tests/test_is_extremal.py

This PR implements the `is_extremal` function, which checks whether a given quantum channel is extremal. The function is based on Section 2.2.4 of Watrous’s *Theory of Quantum Information* and verifies whether the set {A_i† A_j} is linearly independent.
Fixes [#16](https://github.com/vprusso/toqito/issues/16).
-  [x] Implemented the `is_extremal` function in `channel_props/` to determine whether a quantum channel is extremal.
-  [x] Created `test_is_extremal.py` in `channel_props/tests/` to verify the correctness of `is_extremal`.
-  [x] Added support for multiple quantum channel representations, including Kraus operators and Choi matrices.
-  [x] Included test cases for unitary channels, non-extremal channels, Choi matrix input, an example from Watrous's book, and the depolarizing …

Implement is_extremal function and tests for issue #16

---

toqito/state_props/is_unextendible_product_basis.py

There's a missing carriage return in `is_unextendible_product_basis.py` which makes the docs render badly, and potentially skips a doctest. This PR adds it.
I used the following `grep` command to check that it was the only occurence:
```bash
grep -rI -B 1 '>>>' . | grep -vE '>>>|^--$' | grep -v '/docs/
```
-  [x] Verify all previous and newly added unit tests pass in …

Fixed typo is_unextendible_product_basis.py

---

.flake8
pyproject.toml

Ref - #997 
-  [x] Deleted . flake8 file
-  [x] Added E203 to ignore list in pyproject.toml
-  [x] Use `linkcheck` to check for broken links in the …

fix: Remove flake8 (#997)

---

toqito/matrix_ops/calculate_vector_matrix_dimension.py
toqito/nonlocal_games/quantum_hedging.py
toqito/nonlocal_games/xor_game.py
toqito/states/mutually_unbiased_basis.py

Closes #1082.
- Added examples to `matrix_ops/calculate_vector_matrix_dimension`
- Added examples to `states/mutually_unbiased_basis`
- Added examples to `nonlocal_games/quantum_hedging` methods:
- `max_prob_outcome_a_primal`
- `max_prob_outcome_a_dual`
- `min_prob_outcome_a_primal`
- `min_prob_outcome_a_dual`
- Added examples to methods in `nonlocal_games/xor_game`:
- `nonsignaling_value`
-  [x] Use `doctest` to verify the examples in the …

docs: add docstring examples to four public functions

---

docs/contributing.rst
docs/getting_started.rst

As described in #1150, installation of toqito with python 3.13 fails due to cvxopt. Until fixed, this problem will now be mentioned in the documentation under "getting started" and "contributing guide" to simplify installation.
-  [ ] Pointing out python 3.13 is not supported in "Getting started" and "contributing guide"
-  [ ] Verify all previous and newly added unit …

Clarification of documentation in getting started and contributing guide regarding python version

---

toqito/matrices/fourier.py

This PR improves the docstring formatting of the `fourier` function for better readability and accuracy in rendered documentation. It ensures the mathematical expressions for the Fourier matrix are consistent and correctly typeset, without modifying the core logic of the function.
Fixes #1147 
- …

Fixed fourier.py

---

toqito/matrix_props/is_totally_positive.py
toqito/matrix_props/tests/test_is_totally_positive.py

Modifies `is_totally_positive.py` and its corresponding test file to ensure strict positivity of all minors.  
Closes #1098.
- Adjusts test case for identity matrix (identity matrix has minors equal to 0, so it's not totally positive)
- Adds new test case: 2x2 matrix with zero determinant
- Updates logic in `is_totally_positive.py` (line 78) to enforce strict positivity 
-  [x] Use `doctest` to verify the examples in the function docstrings …

fix: enforce strict positivity in is_totally_positive and update tests

---

toqito/matrices/fourier.py

Looks like a few minor lint errors snuck in from https://github.com/vprusso/toqito/pull/1151

fix: fixing ruff lint style in fourier

---

toqito/channel_ops/kraus_to_choi.py

A small addition to the documentation of "kraus_to_choi" clarifies that it's sufficient to only input Kraus operators without their conjugate transpose for CP. This effectively closes issues #79 and #74.
-  [ ] See above.
-  [ ] Check the documentation build does not lead to any failures. `Sphinx` …

Flat list of Kraus operators is possible as input for kraus_to_choi

---

toqito/rand/random_ginibre.py

Fixes a misleading return docstring in the ```random_ginibre``` function that incorrectly labels the output as a "density matrix" instead of a "Ginibre random matrix. Fixes #1157 
-  [x] Updated the return docstring in ```random_ginibre``` to correctly state the output is a "Ginibre random matrix"
- …

Fixed random_ginibre.py

---

toqito/states/ghz.py
toqito/states/tests/test_ghz.py
toqito/states/w_state.py

Closes: #1125 
- Checks if sum of `coeff` list for `ghz.py` and `w_state.py` is close to `1.0`. If not, normalization is carried out.
If this is merged, we can also close out: https://github.com/vprusso/toqito/pull/1127

chore: normalize coeffs if not normalized.

---

toqito/channel_metrics/channel_fidelity.py
toqito/channel_metrics/tests/test_channel_fidelity.py

Closes: #1169 
- Added argument to specify `eps` for threshold to attain solver feasibility.

fix: warning for solver solution channel fidelity.

---

toqito/rand/random_density_matrix.py
toqito/rand/tests/test_random_circulant_gram_matrix.py
toqito/rand/tests/test_random_density_matrix.py
toqito/rand/tests/test_random_ginibre.py
toqito/rand/tests/test_random_orthonormal_basis.py
toqito/rand/tests/test_random_povm.py
toqito/rand/tests/test_random_psd_operator.py
toqito/rand/tests/test_random_state_vector.py
toqito/rand/tests/test_random_states.py
toqito/rand/tests/test_random_unitary.py

Closes: #1166 
The `assert_array_almost_equal` function is internally written in such a way that it converts its inputs to a real type before the comparison. 
When the output density matrix is complex (even if some entries have zero imaginary parts) and it is compared to an expected complex (or sometimes a real) array, the internal conversion may discard the imaginary part. This triggers the warning about “casting complex values to real.”

fix: update np testing for rand functions.

---

docs/requirements.txt

Fixes #1193
Changed documentation dependency syntax from exact version matching (==) to minimum version specifiers (>=) in `docs/requirements.txt`.
This allows for more flexible dependency management while ensuring minimum required versions are met, following PEP 440 version specifier guidelines.
- Updated all 8 dependencies in docs/requirements.txt from `==` to `>=`
- Maintains same minimum version requirements  
- Allows compatible newer versions to be installed

Fix docs dependency syntax to use >= instead of ==

---

toqito/states/bell.py

perf: optimising bell state generation

---

toqito/states/max_entangled.py

```python
def max_entangled_v1(dim: int, is_sparse: bool = False, is_normalized: bool = True) -> [np.ndarray, dia_array]:
mat = eye_array(dim) if is_sparse else np.identity(dim)
psi = np.reshape(mat, (dim**2, 1))
if is_normalized:
psi = psi / np.sqrt(dim)
return psi
```
- Even when the goal is a vector, the function first constructs a full identity matrix (dense or sparse) and then reshapes it into a column vector. For large `dim`, this means allocating and initializing `dim × dim` memory, which is wasteful when only dim non-zero elements are needed.
- Similarly, the sparse branch uses `scipy.sparse.eye_array(dim)`, which still internally builds an identity structure (for matrices) before reshaping, instead of directly creating the sparse vector.
- Normalization is applied to the entire …

perf: optimising max_entangled state generation

---

.github/workflows/benchmark.yml

We introduce a new workflow named `Benchmark Regression Analysis` to support automated performance tracking.
- `target_ref`: commit SHA to benchmark against.
- `benchmark_type`: choose between full and simple benchmark modes.
- `filter / function`: allow filtering tests by name or function pattern.
- `save_results`: optionally store benchmark results for later reference.
- `fail_on_regression`: control whether regressions cause CI failure.
- `regression_threshold`: define acceptable performance deviation.

regression analysis in toqito

---

toqito/matrix_ops/tensor_comb.py
toqito/matrix_ops/tests/test_tensor_comb.py
toqito/matrix_props/tests/test_is_absolutely_k_incoherent.py

Increase test coverage of:
- `tensor_comb.py`
- `is_absolutely_k_incoherent.py`

chore: increase coverage
